[project]
name = "NashOrPass"
version = "0.1.0"
description = ""
authors = [
    {name = "jbaremoney", email = "114310093+jbaremoney@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "rlcard (>=1.2.0,<2.0.0)",
    "torch (==2.2.2)",
    "numpy (<2)",
    "pandas",
    "matplotlib",
    "tqdm",
    "scikit-learn",
    "abstract (>=2025.2.17.0,<2026.0.0.0)",
    "openai (>=2.36.0,<3.0.0)",
    "anthropic (>=0.102.0,<0.103.0)",
    "xai-sdk (>=1.12.2,<2.0.0)"
]

[dependency-groups]
dev = [
    "pytest"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"
[tool.poetry]
packages = [{ include = "NashOrPass", from = "src" }]

